### ISSUE TITLE
عدم امکان استفاده از auto-completion

### ISSUE THREAD

**Issue by ghost** [SharifAIChallenge/AIC20-Client-Python#3]
امکان استفاده از auto-completion و مشاهده متدهای قابل دسترس در محیط ide وجود نداره.  
با مشخص کردن تایپ ورودی و خروجی تابع‌ها به صورت زیر این مشکل میتونه حل بشه.  
```python
def pick(self, world:World):
```
```python
def get_friend(self) -> Player:
```

**Comment by HamidrezaKmK** [comment]
حقیقتش به‌ خاطر اینکه ورژن ۳.۶ به‌ بالا برای این‌کار لازم بود نذاشته بودیم ... اما الان داریم این رو به تمام اینترفیس‌ها اضافه میکنیم به زودی آپدیت می‌شه
