### ISSUE TITLE
def get_paths_crossing_cell 

### ISSUE THREAD

**Issue by mohamad-shadfar** [SharifAIChallenge/AIC20-Client-Python#5]
Hi 
no crossing path return form get_paths_crossing_cell because `cell = self.map.get_cell(row, col)`
must be` cell = self._map.get_cell(row, col)` in bellow function :

 def get_paths_crossing_cell(self, cell=None, row=None, col=None):
        if cell is None:
            if row is None or col is None:
                Logs.show_log("get_paths_crossing cell function called with no valid argument")
                return []
            cell = self.map.get_cell(row, col)

        if not isinstance(cell, Cell):
            Logs.show_log("Given cell is invalid!")
            return []

        paths = []
        for p in self._map.paths:
            if cell in p.cells:
                paths.append(p)
        return paths

**Comment by HamidrezaKmK** [comment]
fixed!
